languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "tuxtorials.com"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  # name = "Your name here"
  # image = "img/author.jpg"
  # headline = "I'm only human"
  # bio = "A little bit about you"
  # links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { facebook = "https://facebook.com/username" },
  #   { github = "https://github.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { instagram = "https://instagram.com/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { telegram = "https://t.me/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  # ]
